run:
  timeout: 5m
  go: '1.23'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - gocognit
    - godot
    - err113
    - exhaustive
    - exportloopref
    - gofumpt
    - gosec
    - nolintlint
    - revive
    - stylecheck
    - whitespace
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  gosec:
    excludes:
      - G404 # Use of weak random number generator

  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false

  stylecheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocyclo
        - gocognit

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
