// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/deals": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list of deals with optional company_id filter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "List deals",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Company ID to filter deals",
                        "name": "company_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.DealsListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_pigeonworks-llc_freee-emulator_internal_models.Deal": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "company_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_pigeonworks-llc_freee-emulator_internal_models.Detail"
                    }
                },
                "due_amount": {
                    "type": "integer"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "issue_date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "partner_code": {
                    "type": "string"
                },
                "partner_id": {
                    "type": "integer"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_pigeonworks-llc_freee-emulator_internal_models.Payment"
                    }
                },
                "ref_number": {
                    "type": "string"
                },
                "type": {
                    "description": "income or expense",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_pigeonworks-llc_freee-emulator_internal_models.Detail": {
            "type": "object",
            "properties": {
                "account_item_id": {
                    "type": "integer"
                },
                "account_item_name": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "item_id": {
                    "type": "integer"
                },
                "item_name": {
                    "type": "string"
                },
                "section_id": {
                    "type": "integer"
                },
                "section_name": {
                    "type": "string"
                },
                "segment_1_tag_id": {
                    "type": "integer"
                },
                "segment_1_tag_name": {
                    "type": "string"
                },
                "segment_2_tag_id": {
                    "type": "integer"
                },
                "segment_2_tag_name": {
                    "type": "string"
                },
                "segment_3_tag_id": {
                    "type": "integer"
                },
                "segment_3_tag_name": {
                    "type": "string"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tag_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tax_code": {
                    "type": "integer"
                },
                "vat": {
                    "type": "integer"
                }
            }
        },
        "github_com_pigeonworks-llc_freee-emulator_internal_models.Payment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "from_walletable_id": {
                    "type": "integer"
                },
                "from_walletable_type": {
                    "description": "bank_account or credit_card",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.DealsListResponse": {
            "type": "object",
            "properties": {
                "deals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_pigeonworks-llc_freee-emulator_internal_models.Deal"
                    }
                }
            }
        },
        "internal_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "error_description": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the access token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/1",
	Schemes:          []string{},
	Title:            "freee API Emulator",
	Description:      "Local emulator for freee accounting API for development and testing",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
